### ISSUE TITLE
Postnet generating script out-of-date

### ISSUE THREAD

**Issue by DatGuy1** [CookiePPP/cookietts#12]
Still seems to use the training format that's in master.

**Comment by CookiePPP** [comment]
I'll update it *soon* (tm). I need to update the inference server a little as the text preprocessor keeps letting chunks larger than the target segment size through which is invalidating my new "Failure Rate" metric/score

---
example output from the ngrok

>Generated 2.566s of audio in 1.161s wall time - so far. (best of 64 tries this pass) (2.21xRT) (0.0%Failure Rate)

The failure rate is measured as a file with weighted attention score under 0.6.
Every generated clip that doesn't make it to the end of the text segment easily gets written off as a failure clip, so that's currently being resolved.

**Comment by CookiePPP** [comment]
![paste](https://user-images.githubusercontent.com/42448678/98951640-6cbddd80-24f2-11eb-99f5-49cc6621b75f.png)
---
GTA.py updated, will start updating HiFi-GAN dataloader when this is done processing.

**Comment by CookiePPP** [comment]
Problem resolved.

**Comment by DatGuy1** [comment]
Hey, unless I'm missing something you never actually updated GTA.py?

**Comment by CookiePPP** [comment]
ah yeah sorry, I'm slowly phasing our the `_1_preprocess` and `_3_generate_postnets` folders.
